//---------------------------------------------------------------------------
//
// SCSI2Pi, SCSI device emulator and SCSI tools for the Raspberry Pi
//
// Contains code generated by Claude AI, guided by Justin Cichra and Uwe Seimet
//
//---------------------------------------------------------------------------

#include "pi5_bus.h"
#include <algorithm>
#include <bit>
#include <thread>
#include <fcntl.h>
#include <sys/epoll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <spdlog/spdlog.h>

using namespace spdlog;

string Pi5Bus::SetUp(bool target)
{
    if (const string &error = GpioBus::SetUp(target); !error.empty()) {
        return error;
    }

    // The interrupts cannot be disabled like on the other Pis, real-time scheduling is used instead.
    // This requires kernel.sched_rt_runtime_us=-1, otherwise the thread is paused for 50 ms every second.
    sched_param param { };
    param.sched_priority = 99;
    pthread_setschedparam(pthread_self(), SCHED_FIFO, &param);

    // Unlike /dev/mem, /dev/gpiomem0 does not require root permissions but membership in the gpio group
    const int fd = open("/dev/gpiomem0", O_RDWR | O_SYNC);
    if (fd == -1) {
        return "Can't open /dev/gpiomem0: "s + system_error(errno, generic_category()).what();
    }
    void *map = mmap(nullptr, MAP_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    close(fd);
    if (map == MAP_FAILED) {
        return "Can't map RP1 GPIO: "s + system_error(errno, generic_category()).what();
    }
    gpio = span(static_cast<volatile uint32_t*>(map), MAP_SIZE / sizeof(uint32_t));

    // Hand all pins over to software control, some of them default to other functions, e.g. SPI0 and UART0.
    // 12 mA is the maximum drive strength.
    for (int pin = PIN_ACT; pin <= PIN_SEL; ++pin) {
        gpio[GetControlRegister(pin)] = (gpio[GetControlRegister(pin)] & ~FUNCSEL_MASK) | FUNCSEL_SYS_RIO;
    }
    SetPads(PAD_DRIVE_12MA);

    InitializeSignals();

    // Set control signals
    PinSetSignal(PIN_ACT, false);
    PinSetSignal(GetPinTad(), false);
    PinSetSignal(GetPinInd(), false);
    PinSetSignal(GetPinDtd(), false);
    SetSignal(PIN_ACT, true);
    SetSignal(GetPinTad(), true);
    SetSignal(GetPinInd(), true);
    SetSignal(GetPinDtd(), true);

    PinSetSignal(PIN_ENB, false);
    SetSignal(PIN_ENB, true);

    // Initialize SEL signal interrupt, the RP1 is the first GPIO chip
    if (const string &error = SetUpSelectionEvent(); !error.empty()) {
        return error;
    }

    // A data pin is asserted by enabling its output
    for (uint32_t i = 0; i < data_oe.size(); ++i) {
        const uint32_t parity = popcount(i) % 2 == 0 ? 1 : 0;
        data_oe[i] = (i | parity << 8) << PIN_DT0;
    }

    if (use_pio) {
        pio = make_unique<Rp1Pio>();
        if (const string &error = pio->Init(gpio, target); !error.empty()) {
            spdlog::error("Error: {}, using slower software handshake", error);
            pio.reset();
        }
    }
    else {
        info("Hardware handshake is disabled");
    }

    // Set the initiator signal direction
    PinSetSignal(GetPinInd(), !target);

    // Set data bus signal directions
    PinSetSignal(GetPinDtd(), target);

    // Set ENABLE in order to show the user that s2p is running
    PinSetSignal(PIN_ENB, true);

    return "";
}

void Pi5Bus::CleanUp()
{
    pio.reset();

    GpioBus::CleanUp();

    // Set control signals
    PinSetSignal(PIN_ENB, false);
    PinSetSignal(PIN_ACT, false);
    PinSetSignal(GetPinTad(), false);
    PinSetSignal(GetPinInd(), false);
    PinSetSignal(GetPinDtd(), false);
    SetSignal(PIN_ACT, false);
    SetSignal(GetPinTad(), false);
    SetSignal(GetPinInd(), false);
    SetSignal(GetPinDtd(), false);

    InitializeSignals();

    SetPads(PAD_DRIVE_8MA);
}

void Pi5Bus::SetDataDirIn(bool in) const
{
    // Change the data input/output direction according to the IO signal
    GpioBus::SetDataDirIn(in);

    // A data pin is asserted by driving it low, which is why the output level of the data pins must always be low
    // in initiator mode, where the IO signal is not controlled by this device
    gpio[RIO_OFFSET + (in || !target_mode ? CLR : SET) + RIO_OUT] = DATA_MASK;
}

int Pi5Bus::TargetSendHandShake(data_out_t buf, int daynaport_delay_after_bytes)
{
    if (!pio || buf.size() < MIN_PIO_BYTES || daynaport_delay_after_bytes != SEND_NO_DELAY) {
        return Bus::TargetSendHandShake(buf, daynaport_delay_after_bytes);
    }

    if (!WaitHandShake(PIN_ACK_MASK, false)) {
        return 0;
    }

    pio_words.resize(buf.size());
    ranges::transform(buf, pio_words.begin(), [this](uint8_t b) { return data_oe[b] >> PIN_DT0; });

    // From here on the PIO drives the data pins
    SetOutputEnable(DATA_MASK, false);

    return pio->TargetSend(pio_words);
}

int Pi5Bus::TargetReceiveHandShake(data_in_t buf)
{
    if (!pio || buf.size() < MIN_PIO_BYTES || buf.size() % 4) {
        return Bus::TargetReceiveHandShake(buf);
    }

    if (!WaitHandShake(PIN_ACK_MASK, false)) {
        return 0;
    }

    // The data pins are inputs during DATA OUT
    SetOutputEnable(DATA_MASK, false);

    return pio->TargetReceive(buf);
}

// For DATA IN
int Pi5Bus::InitiatorReceiveHandShake(data_in_t buf)
{
    // The PIO is only used for DATA IN, because it monitors CD in order to detect the end of the data phase
    if (!pio || buf.size() < MIN_PIO_BYTES || GetPhase() != BusPhase::DATA_IN) {
        return Bus::InitiatorReceiveHandShake(buf);
    }

    // The data pins are inputs during DATA IN
    SetOutputEnable(DATA_MASK, false);

    return pio->InitiatorReceive(buf);
}

// For DATA OUT
int Pi5Bus::InitiatorSendHandShake(data_out_t buf)
{
    // The PIO is only used for DATA OUT, because it monitors CD in order to detect the end of the data phase.
    // COMMAND and MESSAGE OUT (ATN handling) always use the software handshake.
    if (!pio || buf.size() < MIN_PIO_BYTES || GetPhase() != BusPhase::DATA_OUT) {
        return Bus::InitiatorSendHandShake(buf);
    }

    pio_words.resize(buf.size());
    ranges::transform(buf, pio_words.begin(), [this](uint8_t b) { return data_oe[b] >> PIN_DT0; });

    // From here on the PIO drives the data pins
    SetOutputEnable(DATA_MASK, false);

    return pio->InitiatorSend(pio_words);
}

void Pi5Bus::SetDAT(uint8_t dat) const
{
    // Keep the previous byte on the bus until the initiator has released ACK.
    // Without this the Mac Plus crashes while reading from the disk.
    // In initiator mode ACK is controlled by this device, and it has already been released.
    if (target_mode) {
        WaitHandShake(PIN_ACK_MASK, false);
    }

    // Change all data pins with a single atomic XOR of their output enable bits
    gpio[RIO_OFFSET + XOR + RIO_OE] = current_data_oe ^ data_oe[dat];
    current_data_oe = data_oe[dat];
}

void Pi5Bus::InitializeSignals() const
{
    for (const int pin : SIGNAL_TABLE) {
        PinSetSignal(pin, false);
        SetSignal(pin, false);
        gpio[PADS_OFFSET + 1 + pin] = gpio[PADS_OFFSET + 1 + pin] & ~PAD_PULL_MASK;
    }
}

void Pi5Bus::SetSignal(int pin, bool state) const
{
    if (pin >= 0) {
        SetOutputEnable(1U << pin, state);
    }
}

void Pi5Bus::PinSetSignal(int pin, bool state) const
{
    if (pin >= 0) {
        gpio[RIO_OFFSET + (state ? SET : CLR) + RIO_OUT] = 1U << pin;
    }
}

void Pi5Bus::SetOutputEnable(uint32_t mask, bool enable) const
{
    gpio[RIO_OFFSET + (enable ? SET : CLR) + RIO_OE] = mask;

    if (enable) {
        current_data_oe |= mask & DATA_MASK;
    }
    else {
        current_data_oe &= ~mask;
    }
}

void Pi5Bus::SetPads(uint32_t drive) const
{
    for (int pin = PIN_ACT; pin <= PIN_SEL; ++pin) {
        gpio[PADS_OFFSET + 1 + pin] = (gpio[PADS_OFFSET + 1 + pin] & ~(PAD_OUTPUT_DISABLE | PAD_DRIVE_MASK))
            | PAD_INPUT_ENABLE | drive;
    }
}

// The RP1 has no ARM timer, but the Pi 5 has a fast steady clock
void Pi5Bus::WaitNanoSeconds(bool daynaport) const
{
    const auto deadline = chrono::steady_clock::now() + (daynaport ? DAYNAPORT_DELAY : BUS_SETTLE_DELAY);
    while (chrono::steady_clock::now() < deadline) {
        // Intentionally empty
    }
}
