//---------------------------------------------------------------------------
//
// SCSI2Pi, SCSI device emulator and SCSI tools for the Raspberry Pi
//
// Contains code generated by Claude AI, guided by Justin Cichra and Uwe Seimet
//
//---------------------------------------------------------------------------

#include "rp1_pio.h"
#include <algorithm>
#include <array>
#include <cassert>
#include <cerrno>
#include <chrono>
#include <system_error>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include "pi5_bus.h"

// The kernel interface of the rp1-pio driver, provided by the linux-libc-dev package of Raspberry Pi OS
#if __has_include(<misc/rp1_pio_if.h>)
#include <misc/rp1_pio_if.h>
#define HAS_RP1_PIO
#endif

#ifdef HAS_RP1_PIO

namespace
{

constexpr int DATA_PIN_COUNT = 9;

constexpr uint32_t DATA_PIN_MASK = ((1U << DATA_PIN_COUNT) - 1) << PIN_DT0;

// The pins handed over to the PIO: The data pins and the signal driven by the PIO
constexpr uint32_t TARGET_PIN_MASK = DATA_PIN_MASK | 1U << PIN_REQ;
constexpr uint32_t INITIATOR_PIN_MASK = DATA_PIN_MASK | 1U << PIN_ACK;

// The kernel driver uses 4 DMA buffers of this size per direction
constexpr uint16_t DMA_BUFFER_SIZE = 2048;
constexpr uint16_t DMA_BUFFER_COUNT = 4;

// The maximum number of bytes per transfer, a multiple of the sector size
constexpr size_t MAX_TRANSFER_BYTES = 32768;

// The kernel driver aborts a DMA transfer after 1 s without progress, the same applies to the final handshake
constexpr auto HANDSHAKE_TIMEOUT = chrono::seconds(1);

// 31 delay cycles per instruction at 200 MHz, i.e. 6 x 32 cycles (~1 us) between setting the data and REQ
constexpr uint16_t SETTLE_DELAY = 31 << 8;

// pull; out pindirs, 9 (assert the data and parity bits); settle; set pindirs, 1 (assert REQ);
// wait 0 gpio ACK; set pindirs, 0 (release REQ); wait 1 gpio ACK
// loaded directly behind the receive program
constexpr array<uint16_t, 11> TARGET_SEND_PROGRAM = { 0x80a0, 0x6089 | SETTLE_DELAY, 0xa042 | SETTLE_DELAY, 0xa042
    | SETTLE_DELAY, 0xa042 | SETTLE_DELAY, 0xa042 | SETTLE_DELAY, 0xa042 | SETTLE_DELAY, 0xe081, 0x2000 | PIN_ACK,
    0xe080, 0x2080 | PIN_ACK };

// 31 delay cycles (155 ns) between ACK and sampling the data pins, because some data lines settle later than ACK
// TODO Not required by the SCSI specification, which has the initiator drive valid data 55 ns before ACK.
// Find out why the data lines settle late after ACK (a Mac Plus needs at least 80 ns)
constexpr uint16_t SAMPLE_DELAY = 31 << 8;

// The RX DMA only starts after the state machine, so the program first pushes one dummy word more than the
// FIFO holds. The last push completes once the DMA is reading, and only then is the first REQ asserted.
constexpr size_t PRIME_WORDS = 9;

// pull (the byte count - 1); mov x, osr; set y, 8; prime: push; jmp y--, prime;
// loop: set pindirs, 1 (assert REQ); wait 0 gpio ACK; in pins, 8 (4 bytes per FIFO word); set pindirs, 0 (release REQ);
// wait 1 gpio ACK; jmp x--, loop.
// Loaded at offset 0 because of the absolute jump targets. Stalls at "pull" when done.
constexpr array<uint16_t, 11> TARGET_RECEIVE_PROGRAM = { 0x80a0, 0xa027, 0xe040 | (PRIME_WORDS - 1), 0x8020, 0x0083, 0xe081,
    0x2000 | PIN_ACK | SAMPLE_DELAY, 0x4008 | (7 << 8), 0xe080, 0x2080 | PIN_ACK, 0x0045 };

constexpr uint16_t TARGET_SEND_ORIGIN = TARGET_RECEIVE_PROGRAM.size();

static_assert(TARGET_SEND_ORIGIN + TARGET_SEND_PROGRAM.size() <= 32, "The PIO instruction memory has 32 slots");

// Initiator mode
//
// The target drives REQ, and the initiator drives ACK. Both programs wait for REQ and then check CD (JMP_PIN), which
// is released as long as the target stays in a data phase. In any other phase (STATUS, MESSAGE IN, ...) the byte is
// not acknowledged, and the program finishes the transfer in a way that keeps the DMA transfers consistent.
//
// The programs do not contain the instructions for loading the byte count. SetByteCount() puts the count - 1 into
// X by executing "pull" and "mov x, osr" directly. X is decremented once per byte by "jmp x--".
// Both programs stall at a "pull" with an empty FIFO when they are done, so that they never touch the bus
// until the state machine is disabled by the driver.
//
// The jump addresses are absolute, so the programs are loaded at fixed offsets.

// DATA IN. One FIFO word per byte (the inverted data in the lower 8 bits), because the number of bytes that are
// transferred is not known in advance. If the target leaves the data phase early, the remaining words are filled
// with END_OF_DATA, so that the DMA transfer of the host always receives the number of words it expects.
//
//  0  wait 0 gpio REQ [31]   REQ asserted, then let the data lines settle
//  1  jmp pin, 3             CD released: still in the data phase
//  2  jmp 10                 The target has left the data phase, do not acknowledge the byte
//  3  in pins, 8             Sample DT0-DT7
//  4  in null, 24            Zero-extend the byte to a word (autopush)
//  5  set pindirs, 1         Assert ACK
//  6  wait 1 gpio REQ        The target releases REQ
//  7  set pindirs, 0         Release ACK
//  8  jmp x--, 0             Next byte. Falls through when all bytes have been received.
//  9  pull block             Stall (the FIFO is empty)
// 10  mov isr, ~null         Fill up the remaining words with END_OF_DATA
// 11  push block
// 12  jmp x--, 10
// 13  jmp 9
constexpr uint32_t END_OF_DATA = 0xffffffff;

constexpr array<uint16_t, 14> INITIATOR_RECEIVE_PROGRAM = { 0x2000 | PIN_REQ | SAMPLE_DELAY, 0x00c0 | 3, 0x0000 | 10,
    0x4008, 0x4078, 0xe081, 0x2080 | PIN_REQ, 0xe080, 0x0040 | 0, 0x80a0, 0xa0cb, 0x8020, 0x0040 | 10, 0x0000 | 9 };

// The state machine wraps (and stalls) at the "pull" in the middle of the program
constexpr uint16_t INITIATOR_RECEIVE_WRAP_TOP = 9;

constexpr uint16_t INITIATOR_SEND_ORIGIN = INITIATOR_RECEIVE_PROGRAM.size();

// DATA OUT. The words contain the output enable bits like for the target. After the final handshake the program
// pushes a result word: 0 if all bytes have been sent, otherwise the negated number of unsent bytes. If the target
// leaves the data phase early, the program drains the remaining words from the host's DMA transfer first.
//
//  0  wait 0 gpio REQ        REQ asserted
//  1  jmp pin, 3             CD released: still in the data phase
//  2  jmp 13                 The target has left the data phase, do not drive the data pins and do not acknowledge
//  3  pull block             The data of the next byte
//  4  out pindirs, 9 [31]    Assert the data and parity bits
//  5  set y, 4
//  6  jmp y--, 6 [31]        Settle for about 1 us in total, like in the software handshake
//  7  set pindirs, 1         Assert ACK
//  8  wait 1 gpio REQ        The target releases REQ
//  9  set pindirs, 0         Release ACK
// 10  jmp x--, 0             Next byte. Falls through when all bytes have been sent, X is -1.
// 11  push block             Result 0 (the ISR is empty)
// 12  pull block             Stall (the FIFO is empty)
// 13  mov isr, ~x            Result: The negated number of unsent bytes
// 14  pull block             Drain the remaining words
// 15  jmp x--, 14
// 16  jmp 11
constexpr uint16_t O = INITIATOR_SEND_ORIGIN;
constexpr array<uint16_t, 17> INITIATOR_SEND_PROGRAM = { 0x2000 | PIN_REQ, 0x00c0 | (O + 3), 0x0000 | (O + 13), 0x80a0,
    0x6089 | SETTLE_DELAY, 0xe044, 0x0080 | (O + 6) | SETTLE_DELAY, 0xe081, 0x2080 | PIN_REQ, 0xe080, 0x0040 | O, 0x8020,
    0x80a0, 0xa0c9, 0x80a0, 0x0040 | (O + 14), 0x0000 | (O + 11) };

constexpr uint16_t INITIATOR_SEND_WRAP_TOP = O + 12;

static_assert(INITIATOR_SEND_ORIGIN + INITIATOR_SEND_PROGRAM.size() <= 32, "The PIO instruction memory has 32 slots");

// "pull block" and "mov x, osr", executed directly in order to load the byte count
constexpr uint16_t PULL_BLOCK = 0x80a0;
constexpr uint16_t MOV_X_OSR = 0xa027;

// See the PIO chapter of the RP2040 datasheet for the register layout
constexpr uint32_t CLKDIV_1 = 1U << 16;
constexpr uint32_t WRAP_BOTTOM_LSB = 7;
constexpr uint32_t WRAP_TOP_LSB = 12;
constexpr uint32_t JMP_PIN_LSB = 24;
constexpr uint32_t IN_SHIFT_RIGHT = 1U << 18;
constexpr uint32_t OUT_SHIFT_RIGHT = 1U << 19;
constexpr uint32_t AUTOPUSH = 1U << 16;
constexpr uint32_t OUT_BASE_LSB = 0;
constexpr uint32_t SET_BASE_LSB = 5;
constexpr uint32_t IN_BASE_LSB = 15;
constexpr uint32_t OUT_COUNT_LSB = 20;
constexpr uint32_t SET_COUNT_LSB = 26;

// The target programs drive REQ with "set", the initiator programs drive ACK
constexpr uint32_t SET_PIN_REQ = PIN_REQ << SET_BASE_LSB | 1U << SET_COUNT_LSB;
constexpr uint32_t SET_PIN_ACK = PIN_ACK << SET_BASE_LSB | 1U << SET_COUNT_LSB;

}

Rp1Pio::~Rp1Pio()
{
    if (fd != -1) {
        close(fd);
    }
}

string Rp1Pio::Init(span<volatile uint32_t> g, bool t)
{
    gpio = g;
    target = t;
    pin_mask = target ? TARGET_PIN_MASK : INITIATOR_PIN_MASK;

    fd = open("/dev/pio0", O_RDWR | O_CLOEXEC);
    if (fd == -1) {
        return "Can't open /dev/pio0: "s + system_error(errno, generic_category()).what();
    }

    // A mask of 0 claims any unused state machine
    rp1_pio_sm_claim_args claim = { };
    const int s = ioctl(fd, PIO_IOC_SM_CLAIM, &claim);
    if (s < 0) {
        return "Can't claim a PIO state machine: "s + system_error(errno, generic_category()).what();
    }
    sm = static_cast<uint16_t>(s);

    if (const string &error = LoadPrograms(); !error.empty()) {
        return error;
    }

    for (const uint16_t dir : { RP1_PIO_DIR_TO_SM, RP1_PIO_DIR_FROM_SM }) {
        if (rp1_pio_sm_config_xfer_args xfer = { .sm = sm, .dir = dir, .buf_size = DMA_BUFFER_SIZE, .buf_count =
            DMA_BUFFER_COUNT }; !Ioctl(PIO_IOC_SM_CONFIG_XFER, &xfer)) {
            return "Can't configure PIO DMA: "s + system_error(errno, generic_category()).what();
        }
    }

    SetUpStateMachine(false);

    return "";
}

string Rp1Pio::LoadPrograms()
{
    const auto add_program = [this](span<const uint16_t> program, uint16_t origin) {
        rp1_pio_add_program_args args = { .num_instrs = static_cast<uint16_t>(program.size()), .origin = origin,
            .instrs = { } };
        ranges::copy(program, args.instrs);
        return ioctl(fd, PIO_IOC_ADD_PROGRAM, &args);
    };

    // The instruction memory (32 instructions) does not hold the programs of both modes, which is not an issue
    // because we are either in target or in initiator mode
    if (target) {
        if (add_program(TARGET_RECEIVE_PROGRAM, 0) < 0
            || add_program(TARGET_SEND_PROGRAM, TARGET_SEND_ORIGIN) != TARGET_SEND_ORIGIN) {
            return "Can't load the target mode PIO programs: "s + system_error(errno, generic_category()).what();
        }
    }
    else if (add_program(INITIATOR_RECEIVE_PROGRAM, 0) < 0
        || add_program(INITIATOR_SEND_PROGRAM, INITIATOR_SEND_ORIGIN) != INITIATOR_SEND_ORIGIN) {
        return "Can't load the initiator mode PIO programs: "s + system_error(errno, generic_category()).what();
    }

    return "";
}

int Rp1Pio::TargetSend(span<uint32_t> data)
{
    Start();

    // One word per byte
    const size_t sent = Transfer(RP1_PIO_DIR_TO_SM, as_writable_bytes(data)) / sizeof(uint32_t);

    // The DMA transfer has finished, but the last bytes may still be in the FIFO
    const bool success = sent == data.size() && WaitForCompletion(true);

    SetUpStateMachine(false);

    return success ? static_cast<int>(data.size()) : static_cast<int>(sent);
}

int Rp1Pio::TargetReceive(data_in_t buf)
{
    assert(!buf.empty() && !(buf.size() % 4));

    SetUpStateMachine(true);

    rp1_pio_sm_put_args put = { .sm = sm, .blocking = 1, .rsvd = 0, .data = static_cast<uint32_t>(buf.size() - 1) };
    Ioctl(PIO_IOC_SM_PUT, &put);
    Start();

    // Four bytes per word, after the dummy words
    words.resize(PRIME_WORDS + (buf.size() / 4));
    const size_t transferred = Transfer(RP1_PIO_DIR_FROM_SM, as_writable_bytes(span(words))) / sizeof(uint32_t);
    const size_t received = transferred > PRIME_WORDS ? transferred - PRIME_WORDS : 0;

    const bool success = transferred == words.size() && WaitForCompletion(false);

    SetUpStateMachine(false);

    for (size_t i = 0; i < received; ++i) {
        // Invert because of negative logic, the first byte is in the lowest 8 bits
        const uint32_t w = ~words[PRIME_WORDS + i];
        for (size_t j = 0; j < 4; ++j) {
            buf[i * 4 + j] = static_cast<uint8_t>(w >> (8 * j));
        }
    }

    return success ? static_cast<int>(buf.size()) : static_cast<int>(received * 4);
}

int Rp1Pio::InitiatorSend(span<uint32_t> data)
{
    assert(!data.empty());

    // The state machine is already set up for sending
    SetByteCount(data.size());
    Start();

    // One word per byte
    const size_t sent = Transfer(RP1_PIO_DIR_TO_SM, as_writable_bytes(data)) / sizeof(uint32_t);

    // The program reports the number of unsent bytes (negated) after the final handshake, so reading the result
    // also waits for the handshake of the last byte
    uint32_t result = 0;
    const bool completed = sent == data.size()
        && Transfer(RP1_PIO_DIR_FROM_SM, as_writable_bytes(span(&result, 1))) == sizeof(result);

    if (!completed) {
        // Do not leave a stale result in the DMA buffers
        Abort(RP1_PIO_DIR_FROM_SM);

        // The final handshake is unconfirmed, so never report the transfer as complete
        return static_cast<int>(min(sent, data.size() - 1));
    }

    SetUpStateMachine(false);

    const size_t unsent = 0U - result;

    return unsent <= data.size() ? static_cast<int>(data.size() - unsent) : 0;
}

int Rp1Pio::InitiatorReceive(data_in_t buf)
{
    assert(!buf.empty());

    SetUpStateMachine(true);
    SetByteCount(buf.size());
    Start();

    // One word per byte
    words.resize(buf.size());
    const size_t received = Transfer(RP1_PIO_DIR_FROM_SM, as_writable_bytes(span(words))) / sizeof(uint32_t);

    // The DMA transfer has finished, but the handshake of the last byte may still be running
    const bool success = received == words.size() && WaitForCompletion(false);

    SetUpStateMachine(false);

    // If the target has left the data phase, the PIO has filled up the remaining words with END_OF_DATA
    size_t count = 0;
    while (count < received && words[count] != END_OF_DATA) {
        // Invert because of negative logic
        buf[count] = static_cast<uint8_t>(~words[count]);
        ++count;
    }

    return static_cast<int>(success ? count : min(count, buf.size() - 1));
}

bool Rp1Pio::Ioctl(unsigned long request, void *args) const // NOSONAR void * cannot be replaced
{
    return ioctl(fd, request, args) >= 0;
}

// Returns the number of bytes transferred
size_t Rp1Pio::Transfer(uint16_t dir, span<byte> data)
{
    size_t transferred = 0;
    while (transferred < data.size()) {
        const size_t count = min(data.size() - transferred, MAX_TRANSFER_BYTES);
        // Older kernel headers have no rsvd member, so the members are assigned individually
        rp1_pio_sm_xfer_data_args xfer = { };
        xfer.sm = sm;
        xfer.dir = dir;
        xfer.data_bytes = static_cast<uint16_t>(count);
        xfer.data = data.subspan(transferred).data();
        if (!Ioctl(PIO_IOC_SM_XFER_DATA, &xfer)) {
            Abort(dir);
            break;
        }
        transferred += count;
    }

    return transferred;
}

// Hand the pins over to the PIO and start the state machine
void Rp1Pio::Start() const
{
    SetPinFunction(Pi5Bus::FUNCSEL_PIO);
    rp1_pio_sm_set_enabled_args enable = { .mask = static_cast<uint16_t>(1U << sm), .enable = 1, .rsvd = 0 };
    Ioctl(PIO_IOC_SM_SET_ENABLED, &enable);
}

// Disable the state machine, release the pins and prepare the program for the next transfer
void Rp1Pio::SetUpStateMachine(bool receive)
{
    rp1_pio_sm_set_enabled_args disable = { .mask = static_cast<uint16_t>(1U << sm), .enable = 0, .rsvd = 0 };
    Ioctl(PIO_IOC_SM_SET_ENABLED, &disable);

    SetPinFunction(Pi5Bus::FUNCSEL_SYS_RIO);

    uint16_t start;
    uint16_t end;
    uint32_t signal_pinctrl;
    uint32_t execctrl_flags = 0;
    if (target) {
        start = receive ? 0 : TARGET_SEND_ORIGIN;
        end = start + static_cast<uint16_t>(receive ? TARGET_RECEIVE_PROGRAM.size() : TARGET_SEND_PROGRAM.size()) - 1;
        signal_pinctrl = SET_PIN_REQ;
    }
    else {
        // The initiator programs stall at their last wrapped instruction
        start = receive ? 0 : INITIATOR_SEND_ORIGIN;
        end = receive ? INITIATOR_RECEIVE_WRAP_TOP : INITIATOR_SEND_WRAP_TOP;
        signal_pinctrl = SET_PIN_ACK;
        execctrl_flags = static_cast<uint32_t>(PIN_CD) << JMP_PIN_LSB;
    }
    start_pc = start;

    rp1_pio_sm_init_args init = { .sm = sm, .initial_pc = start, .config = {
        .clkdiv = CLKDIV_1,
        .execctrl = static_cast<uint32_t>(start) << WRAP_BOTTOM_LSB | static_cast<uint32_t>(end) << WRAP_TOP_LSB
            | execctrl_flags,
        .shiftctrl = IN_SHIFT_RIGHT | OUT_SHIFT_RIGHT | (receive ? AUTOPUSH : 0),
        .pinctrl = signal_pinctrl
            | (receive ? PIN_DT0 << IN_BASE_LSB : PIN_DT0 << OUT_BASE_LSB | DATA_PIN_COUNT << OUT_COUNT_LSB) } };
    Ioctl(PIO_IOC_SM_INIT, &init);

    rp1_pio_sm_clear_fifos_args clear = { .sm = sm };
    Ioctl(PIO_IOC_SM_CLEAR_FIFOS, &clear);
    rp1_pio_sm_set_pins_args pins = { .sm = sm, .rsvd = 0, .values = 0, .mask = pin_mask };
    Ioctl(PIO_IOC_SM_SET_PINS, &pins);
    rp1_pio_sm_set_pindirs_args pindirs = { .sm = sm, .rsvd = 0, .dirs = 0, .mask = pin_mask };
    Ioctl(PIO_IOC_SM_SET_PINDIRS, &pindirs);
    rp1_pio_sm_restart_args restart = { .mask = static_cast<uint16_t>(1U << sm) };
    Ioctl(PIO_IOC_SM_RESTART, &restart);
    // jmp start
    rp1_pio_sm_exec_args exec = { .sm = sm, .instr = start, .blocking = 0, .rsvd = 0 };
    Ioctl(PIO_IOC_SM_EXEC, &exec);
}

// The initiator programs have no instructions for loading X. Instead, the count is put into the TX FIFO and the
// state machine is made to execute "pull" and "mov x, osr", followed by a jump to the start of the program.
void Rp1Pio::SetByteCount(size_t count) const
{
    rp1_pio_sm_put_args put = { .sm = sm, .blocking = 1, .rsvd = 0, .data = static_cast<uint32_t>(count - 1) };
    Ioctl(PIO_IOC_SM_PUT, &put);

    // The last instruction is "jmp start"
    for (const uint16_t instr : { PULL_BLOCK, MOV_X_OSR, start_pc }) {
        rp1_pio_sm_exec_args exec = { .sm = sm, .instr = instr, .blocking = 0, .rsvd = 0 };
        Ioctl(PIO_IOC_SM_EXEC, &exec);
    }
}

// Switch the pins used by the PIO between PIO and software control
void Rp1Pio::SetPinFunction(uint32_t function) const
{
    for (int pin = 0; pin < 32; ++pin) {
        if (pin_mask & 1U << pin) {
            const int reg = Pi5Bus::GetControlRegister(pin);
            gpio[reg] = (gpio[reg] & ~Pi5Bus::FUNCSEL_MASK) | function;
        }
    }
}

// Wait for the handshake of the last byte, i.e. until REQ and ACK have been released for several consecutive reads.
// In initiator mode only ACK is checked, because the target may already have asserted REQ for the next phase.
bool Rp1Pio::WaitForCompletion(bool check_fifo) const
{
    const auto deadline = chrono::steady_clock::now() + HANDSHAKE_TIMEOUT;
    int idle_count = 0;
    while (idle_count < 4) {
        if (chrono::steady_clock::now() > deadline) {
            return false;
        }

        rp1_pio_sm_fifo_state_args fifo = { .sm = sm, .tx = 1, .rsvd = 0, .level = 0, .empty = 1, .full = 0 };
        if (check_fifo) {
            Ioctl(PIO_IOC_SM_FIFO_STATE, &fifo);
        }

        // Signals are active low
        const uint32_t signals = gpio[Pi5Bus::RIO_OFFSET + Pi5Bus::RIO_SYNC_IN];
        const bool req_released = !target || (signals & (1U << PIN_REQ));
        if (fifo.empty && req_released && (signals & (1U << PIN_ACK))) {
            ++idle_count;
        }
        else {
            idle_count = 0;
        }
    }

    return true;
}

// The other side stopped the handshake. Reconfiguring the DMA terminates the pending transfer.
void Rp1Pio::Abort(uint16_t dir)
{
    SetUpStateMachine(false);

    rp1_pio_sm_config_xfer_args xfer = { .sm = sm, .dir = dir, .buf_size = DMA_BUFFER_SIZE, .buf_count =
        DMA_BUFFER_COUNT };
    Ioctl(PIO_IOC_SM_CONFIG_XFER, &xfer);
}

#else

Rp1Pio::~Rp1Pio() = default;

string Rp1Pio::Init(span<volatile uint32_t>, bool) // NOSONAR Cannot be const in order to be compatible with the PIO implementation
{
    return "This build does not support the RP1 PIO";
}

int Rp1Pio::TargetSend(span<uint32_t>) // NOSONAR Cannot be const in order to be compatible with the PIO implementation
{
    return 0;
}

int Rp1Pio::TargetReceive(data_in_t) // NOSONAR Cannot be const in order to be compatible with the PIO implementation
{
    return 0;
}

int Rp1Pio::InitiatorSend(span<uint32_t>) // NOSONAR Cannot be const in order to be compatible with the PIO implementation
{
    return 0;
}

int Rp1Pio::InitiatorReceive(data_in_t) // NOSONAR Cannot be const in order to be compatible with the PIO implementation
{
    return 0;
}

#endif
