//---------------------------------------------------------------------------
//
// SCSI2Pi, SCSI device emulator and SCSI tools for the Raspberry Pi
//
// Contains code generated by Claude AI, guided by Justin Cichra and Uwe Seimet
//
// Pi 5: The REQ/ACK handshake of DATA IN and DATA OUT runs on a state machine of the RP1 PIO.
// Polling the RP1 GPIO over PCIe takes too long for initiators like the Mac Plus, which use blind
// transfers without checking REQ for each byte.
//
// In initiator mode the PIO follows the REQ signal of the target and drives ACK (and the data pins
// for DATA OUT). It also monitors CD, so that a transfer ends without acknowledging a byte when the
// target leaves the data phase, e.g. for STATUS.
//
//---------------------------------------------------------------------------

#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <vector>
#include "shared/s2p_defs.h"

class Rp1Pio
{

public:

    Rp1Pio() = default;
    ~Rp1Pio();
    Rp1Pio(const Rp1Pio&) = delete;
    Rp1Pio& operator=(const Rp1Pio&) = delete;

    // The RP1 GPIO registers mapped by Pi5Bus, target mode, PIO enabled.
    // The PIO programs depend on the mode, the instruction memory is too small for both sets of programs.
    // Wait for DMA (target mode): For initiators that send DATA OUT bytes without waiting for REQ, e.g. a Mac Plus.
    // The first REQ is only asserted once the receive DMA is running.
    string Init(span<volatile uint32_t>, bool, bool);

    // Target mode: Each word contains the output enable bits of a data byte and its parity (DT0-DT7, DP)
    int TargetSend(span<uint32_t>);

    // Target mode: The number of bytes must be a multiple of 4
    int TargetReceive(data_in_t);

    // Initiator mode: Same word format as for Send(). Returns the number of bytes transferred, which is less
    // than requested if the target has left the DATA OUT phase early.
    int InitiatorSend(span<uint32_t>);

    // Initiator mode: Returns the number of bytes transferred, which is less than requested if the target has
    // left the DATA IN phase early.
    int InitiatorReceive(data_in_t);

private:

    string LoadPrograms();

    bool Ioctl(unsigned long, void*) const;

    size_t Transfer(uint16_t, span<byte>);

    void Start() const;

    void SetUpStateMachine(bool);

    // Initiator mode: Loads the number of bytes - 1 into X, and jumps to the start of the program
    void SetByteCount(size_t) const;

    void SetPinFunction(uint32_t) const;

    bool WaitForCompletion(bool) const;

    void Abort(uint16_t);

    int fd = -1;

    uint16_t sm = 0;

    // The first instruction of the program the state machine is currently set up for
    uint16_t start_pc = 0;

    bool target = true;

    // Target mode: The receive program (the send program starts behind it) and the number of dummy words it pushes
    // before the first REQ
    span<const uint16_t> receive_program;
    size_t prime_words = 0;

    // The pins that are handed over to the PIO during a transfer
    uint32_t pin_mask = 0;

    span<volatile uint32_t> gpio;

    vector<uint32_t> words;
};
