.TH s2p 1
.SH NAME
s2pctl \- SCSI2Pi Server Controller Tool
.SH SYNOPSIS
.B scsictl
[\fB\--id/i\fR \fIID[:LUN]\fR] |
[\fB\--list-extensions/-m\fR] |
[\fB\--list-images/-e\fR] |
[\fB\--list-operations/-o\fR] |
[\fB\--help/-h\fR] |
[\fB\--version/-v\fR] |
[\fB\--server-version/-V\fR] |
[\fB\--detach-all-D\fR] |
[\fB\--list-interfaces/-N\fR] |
[\fB\--list-reserved-ids/-I\fR] |
[\fB\--list-devices/-l\fR] |
[\fB\--list-log-levels\fR] |
[\fB\--list-properties/-P\fR] |
[\fB\--list-statistics/-S\fR] |
[\fB\--list-device-types/-T\fR] |
[\fB\--shut-down/-X\fR] |
[\fB\--prompt\fR] |
[\fB\--text-protobuf\fR] |
[\fB\--binary-protobuf\fR \fIFILENAME\fR] |
[\fB\--json-protobuf\fR \fIFILENAME\fR] |
[\fB\--delete/-d\fR \fIFILENAME\fR] |
[\fB\--create/-C\fR \fIFILENAME:FILESIZE\fR] |
[\fB\--list-image-info/-E\fR \fIFILENAME\fR] |
[\fB\--image-folder/-F\fR \fIIMAGE_FOLDER\fR] |
[\fB\--rename/-R\fR \fICURRENT_NAME:NEW_NAME\fR] |
[\fB\--cmd/-c\fR \fICOMMAND\fR] |
[\fB\--block-size/-b\fR \fIBLOCK_SIZE\fR] |
[\fB\--file/f\fR \fIFILE|PARAM\fR] |
[\fB\--log-level/-L\fR \fILOG_LEVEL\fR] |
[\fB\--host/-H\fR \fIHOST\fR] |
[\fB\--name/-n\fR \fINAME\fR \fIVENDOR:NAME_REVISION\fR] |
[\fB\--port/-p\fR \fIPORT\fR] |
[\fB\--reserve_ids/-r\fR \fIRESERVED_IDS\fR] |
[\fB\--list-settings/-s\fR \fI[FOLDER_PATTERN:FILE_PATTERN:OPERATIONS]\fR] |
[\fB\--type/-t\fR \fITYPE\fR] |
[\fB\--copy/-x\fR \fICURRENT_NAME:NEW_NAME\fR] |
[\fB\--locale\fR \fILOCALE\fR]
.SH DESCRIPTION
.B s2pctl
sends commands to s2p in order to make configuration adjustments at runtime or to check the device status.

You do not need root privileges to use s2pctl. s2pctl also runs on non-Pi Linux platforms. In this case use the -h option to specify the s2p host s2pctl shall connect to.

When launched without arguments s2pctl enters interactive mode where you can enter commands on the command line.

.SH OPTIONS
.TP
.BR \-id/-i\fI " " \fIID[:LUN]
The SCSI or SASI ID and optional LUN that you want to control. (0-7:0-31 for SCSI, 0-7:0-1 for SASI.)
.TP
.BR \--create/-C\fI " "\fIFILENAME:FILESIZE
Create an image file in the default image folder with the specified name and size in bytes.
.TP
.BR \--detach-all/-D\fI
Detach all devices.
.TP
.BR \--list-image-info/-E\fI " " \fIFILENAME
Display image file information.
.TP
.BR \--image-folder/-F\fI " "\fIIMAGE_FOLDER
Set the default image folder.
.TP
.BR \-list-reserved-ids/-I\fI
Display reserved device IDs.
.TP
.BR \--log-level/-L\fI " "\fILOG_LEVEL[:ID[:LUN]]
Set the s2p log level (trace, debug, info, warning, error, off).
.TP
.BR \--host/-H\fI " " \fIHOST
The s2p host to connect to, default is 'localhost'.
.TP
.BR \--list-images/-e\fI
List all images files in the default image folder.
.TP
.BR \--list-interfaces/-N\fI
Lists all network interfaces that are up and available for setting up a DaynaPort emulation.
.TP
.BR \--list-log-levels\fI
Display the available s2p log levels and the current log level.
.TP
.BR \--prompt\fI
Prompt for the access token in case s2p requires authentication.
.TP
.BR \--list-devices/-l\fI
List all of the devices that are currently being emulated, as well as their current status.
.TP
.BR \--list-extensions/-m\fI
List all supported file extensions and the device types they map to.
.TP
.BR \--list-images/-m\fI
List images files in the default image folder.
.TP
.BR \--list-operations/-o\fI
List available remote interface operations.
.TP
.BR \--rename/-R\fI " "\fICURRENT_NAME:NEW_NAME
Rename an image file in the default image folder.
.TP
.BR \--port/-p\fI " " \fIPORT
The s2p port to connect to, default is 6868.
.TP
.BR \--list-properties/-P\fI " " \fIPORT
Display s2p startup properties.
.TP
.BR \--reserve-ids/-r\fI " " \fIRESERVED_IDS
Comma-separated list of IDs to reserve. Pass an empty list in order to not reserve anything.
.TP
.BR \--list-settings/-s\fI " " \fI[FOLDER_PATTERN:FILE_PATTERN:OPERATIONS]
Display all s2p settings. Filenames are optionally filtered by folder and file patterns.
OPERATIONS is an optional comma-seperated list of server operations to take into account, in order to limit the amount of output. 
.TP
.BR \--list-statistics/-S\fI
Display s2p statistics.
.TP
.BR \--list-device-types/-T\fI
Display available device types and their properties.
.TP
.BR \--help/-h\fI " " \fI
Display usage information.
.TP
.BR \-version/-v\fI " " \fI
Display the s2pctl version.
.TP
.BR \--server-version/-V\fI " " \fI
Display the s2p server version.
.TP
.BR \--shut-down/-X\fI " " \fI
Shut down the s2p process.
.TP
.BR \--delete/-d\fI " "\fIFILENAME
Delete an image file in the default image folder.
.TP
.BR \--binary-protobuf\fI " "\fIFILENAME
Do not send command to s2p but write it to a protobuf binary file.
.TP
.BR \--json-protobuf\fI " "\fIFILENAME
Do not send command to s2p but write it to a protobuf JSON file.
.TP
.BR \--text-protobuf\fI " "\fIFILENAME
Do not send command to s2p but write it to a protobuf text format file.
.TP
.BR \--copy/-x\fI " "\fICURRENT_NAME:NEW_NAME
Copy an image file in the default image folder.
.TP
.BR \--locale\fI " "\fILOCALE
Overrides the default locale (language) for client-facing error messages.
.TP 
.BR \--command/-c\fI " " \fICOMMAND
Command is the operation being requested. Options are:
   a(ttach): Attach device
   d(etach): Detach device
   i(nsert): Insert medium (removable media devices only)
   e(ject): Eject medium (removable media devices only)
   p(rotect): Write protect the medium (not for CD-ROMs, which are always read-only)
   u(nprotect): Remove write protection from the medium (not for CD-ROMs, which are always read-only)
.IP
eject, protect and unprotect are idempotent.
.TP 
.BR \--block-size/-b\fI " " \fIBLOCK_SIZE
The optional block size, either 256, 512, 1024, 2048 or 4096 bytes. The default size is 512 bytes.
.TP
.BR \--file/-f\fI " " \fIFILE|PARAM
Device-specific: Either a path to a disk image file, or a parameter for a non-disk device. See the s2p(1) man page for permitted file types.
.TP 
.BR \--type/-t\fI " " \fITYPE
Specifies the device type. This type overrides the type derived from the file extension of the specified image. See the s2p(1) man page for the available device types. For some types there are shortcuts (only the first letter is required):
   hd: SCSI hard disk drive
   rm: SCSI removable media drive
   cd: CD-ROM
   mo: Magneto-Optical disk
   lp: SCSI printer
   daynaport: DaynaPort network adapter
   services: Host services device
.TP 
.BR \--name/-n\fI " " \fIVENDOR:PRODUCT:REVISION
The optional vendor, product and revision for the device, to be returned with the SCSI INQUIRY data. A complete set of name components must be provided. VENDOR may have up to 8, PRODUCT up to 16, REVISION up to 4 characters. Padding with blanks to the maxium length is automatically applied. Once set the name of a device cannot be changed.
.TP 
.BR \-u\fI " " \fIUNIT
Unit number (0-31 for SCSI, 0-1 for SASI). This defaults to 0. This option is only used when there are multiple SCSI/SASI devices for the same SCSI ID.

.SH EXAMPLES
Show a listing of all devices and their current status.
   s2pctl -l


Example output:
   +----+-----+------+-------------------------------------
   | ID | LUN | TYPE | IMAGE FILE
   +----+-----+------+-------------------------------------
   |  0 |   1 | SCHD | /home/pi/images/harddisk.hds
   +----+-----+------+-------------------------------------

Request s2p to attach a disk (assumed) to SCSI ID 0 with the contents of the file system image "HDIIMAGE0.HDS".
   s2pctl -i 0 -f hdimage0.hds

.SH SEE ALSO
s2p(1), s2pexec(1), s2pdump(1)

Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
