.TH s2pdump 1
.SH NAME
s2pdump \- SCSI/SASI drive dump/restore tool for SCSI2Pi
.SH SYNOPSIS
.B s2pdump
[\fB\--scsi-id/-i\fR \fIID[:LUN]\fR]
[\fB\--sasi-id/-h\fR \fIID[:LUN]\fR]
[\fB\--board-id/-B\fR \fIBOARD_ID\fR]
[\fB\--image-file/-f\fR \fIIMAGE_FILE\fR]
[\fB\--buffer-size/-b\fR \fIBUFFER_SIZE\fR]
[\fB\--inquiry/-I\fR] \fID[:LUN]\fR
[\fB\--log-level/-L\fR \fILOG_LEVEL\fR]
[\fB\--scsi-scan/-s\fR]
[\fB\--sasi-scan/-t\fR]
[\fB\--start-sector/-S\fR \fISTART\fR]
[\fB\--sector-count/-C\fR \fICOUNT\fR]
[\fB\--sasi-capacity/-c\fR \fICAPACITY\fR]
[\fB\--sasi-sector-size/-z\fR \fISECTOR_SIZE\fR]
[\fB\--all-luns/-a\fR]
[\fB\--restore/-r\fR]

.SH DESCRIPTION
.B s2pdump
has two modes of operation: dump and restore. These can be used with physical storage media like hard drives and magneto optical drives. Dump mode can be used with read-only media such as CD/DVD drives.

When operating in dump mode, s2pdump will copy all data from a remote drive to an image on the local filesystem. Optionally it generates a .properties file for the web UI. This file can be used to more closely emulate the source drive.

In restore mode s2pdump copies the data from a local image to a remote physical drive. The remote drive must be writable. 

.SH NOTES

.B s2pdump
requires a FULLSPEC PiSCSI/RaSCSI board.

Usually in order to use the generated drive image with SCSI2Pi, it should be moved to the ~/images folder (or the location specified to s2p).

.SH OPTIONS
.TP
.BR --scsi-id/-i\fI " "\fIID[:LUN]
ID and optional LUN (0-31) of the SCSI target drive.
.TP
.BR --sasi-id/-h\fI " "\fIID[:LUN]
ID and optional LUN (0-1) of the SASI target drive.
.TP
.BR --board-id/-B\fI " "\fIBOARD_ID
SCSI ID of the SCSI2Pi board. If not specified ID 7 is used. The SCSI2Pi host will be functioning as the "initiator" device. Not relevant for SASI.
.TP
.BR --image-file/-f\fI " "\fIIMAGE_FILE
Path to the dump/restore file.
.TP
.BR --buffer-size/-b\fI " "\fIBUFFER_SIZE
The transfer buffer size in bytes. The default size is 1 MiB, the minimum size is 64 KiB.
.TP
.BR --inquiry/-I\fI " "\fIID[:LUN]
Display INQUIRY data of ID[:LUN] and (SCSI only) device properties for use with property files, e.g. /etc/s2p.conf.
.TP
.BR --log-level/-L\fI " " \fILOG_LEVEL
Set the log level (trace, debug, info, warning, error, critical, off). The default log level is 'info'.
.TP
.BR --scsi-scan/-s\fI
Scan the bus for SCSI devices and display their properties.
.TP
.BR --sasi-scan/-t\fI
Scan the bus for SASI devices and display their properties.
.TP
.BR --start-sector/-S\fI "  " \fISTART
Start sector for the dump/restore operation, the default is 0.
.TP
.BR --sector-count/-C\fI "  " \fICOUNT
Sector count for the dump/restore operation, the default is the drive capacity.
.TP
.BR --sasi-capacity/-c\fI " "\fISASI_CAPACITY
The capacity of the SASI hard drive in sectors. This parameter only has a meaning for SASI drives.
.TP
.BR --sasi-sector-size/-z\fI " "\fISASI_SECTOR_SIZE
The sector size of the SASI hard drive in sectors (256, 512, x1024) in bytes. This parameter only has a meaning for SASI drives.
.TP
.BR --all-luns/-a\fI
Check all LUNs during bus scan. The default is to scan LUN 0 only.
If the target device supports the REPORT LUNS SCSI command s2pdump uses this command to optimize the scan.
.TP
.BR --restore/-r\fI
Run in restore mode. The default is dump mode.

.SH EXAMPLES
Dump Mode: [SCSI/SASI Drive] ---> [SCSI2Pi host]
Launch s2pdump to dump all data from the drive with SCSI ID 3 with a dump buffer size of 128 KiB. Store it on the local filesystem as a drive image named out_image.hds.
   s2pdump -i 3 -f out_image.hds -b 131072

Restore Mode: [SCSI2Pi host] ---> [SCSI/SASI Drive]
Launch s2pdump to restore/upload a drive image from the local file system to SCSI ID 0 with a restore buffer size of 1 MiB:
   s2pdump -r -i 0 -f in_image.hds -b 1048576

.SH SEE ALSO
s2p(1), s2pctl(1), s2pexec(1), s2pproto(1), s2psimh(1), s2ptool(1)
 
Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
