.TH s2pexec 1
.SH NAME
s2pexec \- SCSI command execution tool for SCSI2Pi
.SH SYNOPSIS
.B s2pexec
\fB\--scsi-target/-s\fR \fIID[:LUN]\fR
[\fB\--board-id/-B\fR \fIBOARD_ID\fR]
[\fB\--log-level/-L\fR \fILOG_LEVEL\fR]
\fB\--input-file/-f\fR \fIINPUT_FILE\fR
[\fB\--output-file/-F\fR \fIOUTPUT_FILE\fR]
[\fB\--binary-input\fR]
[\fB\--binary-output\fR]
[\fB\--text-input\fR]
[\fB\--text-output\fR]
[\fB\--shut-down/-X\fR]
.SH DESCRIPTION
.B s2pexec
wraps protobuf input data into a custom SCSI2Pi SCSI command. s2p executes this command and displays the results. The input data must be a legal command defined in the SCSI2Pi protobuf interface. See the file s2p_interface.proto for details.

.SH NOTES

.B s2pexec
helps with advanced testing. It requires two connected PiSCSI/RaSCSI boards. The board s2pexec is running on must be a FULLSPEC board because s2pexec requires SCSI initiator support.

.SH OPTIONS
.TP
.BR \--scsi-target/-s\fI " "\fIID[:LUN]
SCSI ID and optional LUN of the second PiSCSI/RaSCSI board, which is the target device.
.TP
.BR \--board-id/-B\fI " "\fIBOARD_ID
SCSI ID used by s2pexec. If not specified, s2pexec will use the board (initiator) ID 7.
.TP
.BR \--log-level/-L\fI " " \fILOG_LEVEL
Set the log level (trace, debug, info, warning, error, off). The default log level is 'info'.
.TP
.BR \--input-file/-f\fI " "\fIINPUT_FILE
The protobuf data input file, by default in JSON format.
.TP
.BR \--output-file/-F\fI " "\fIOUTPUT_FILE
The protobuf data output file, by default in JSON format. If not specified JSON data will be displayed on stdout.
.TP
.BR \--binary-input\fI
Signals that the input file is in protobuf binary format instead of JSON.
.TP
.BR \--binary-output\fI
Generate a protobuf binary format file instead of JSON.
.TP
.BR \--text-input\fI
Signals that the input file is in protobuf text format instead of JSON.
.TP
.BR \--text-output\fI
Generate a protobuf text format file instead of JSON.
.TP
.BR \--shut-down/-X\fI
Shut down s2p running on the second board by sending a SCSI command.

.SH SEE ALSO
s2pctl(1), s2p(1), s2pdump(1)
 
Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
