.TH s2pexec 1
.SH NAME
s2pexec \- SCSI2Pi SCSI/SASI command execution
.SH SYNOPSIS
.B s2pexec
[\fB\--scsi-target/-i\fR \fIID[:LUN]\fR]
[\fB\--sasi-target/-h\fR \fIID[:LUN]\fR]
[\fB\--board-id/-B\fR \fIBOARD_ID\fR]
[\fB\--cdb/-c\fR \fICDB\fR]
[\fB\--buffer-size/-b\fR \fIBUFFER_SIZE\fR]
[\fB\--log-level/-L\fR \fILOG_LEVEL\fR]
{\fB\--binary-data-file/-d\fR \fIFILE\fR]
{\fB\--text-data-file/-D\fR \fIFILE\fR]
{\fB\--input-file/-f\fR \fIFILE\fR]
{\fB\--input-file/-f\fR \fIFILE\fR]
[\fB\--output-file/-F\fR \fIFIL\fR]
[\fB\--binary-input\fR]
[\fB\--binary-output\fR]
[\fB\--text-input\fR]
[\fB\--text-output\fR]
[\fB\--help/-H\fR] |
[\fB\--version/-v\fR] |
.SH DESCRIPTION
.B s2pexec
wraps protobuf input data into a custom SCSI2Pi SCSI or SASI command. s2p executes this command and displays the results. The input data must be a legal command defined in the SCSI2Pi protobuf interface. See the file s2p_interface.proto for details.

.SH NOTES

.B s2pexec
helps with advanced testing. It requires two connected PiSCSI/RaSCSI boards. The board s2pexec is running on must be a FULLSPEC board because s2pexec requires SCSI initiator support.

.SH OPTIONS
.TP
.BR \--scsi-target/-i\fI " "\fIID[:LUN]
SCSI ID and optional LUN (0-31) of the second PiSCSI/RaSCSI board, which is the target SCSI device.
.TP
.BR \--scsi-target/-h\fI " "\fIID[:LUN]
SASI ID and optional LUN (0-1) of the second PiSCSI/RaSCSI board, which is the target SASI device.
.TP
.BR \--board-id/-B\fI " "\fIBOARD_ID
SCSI ID used by s2pexec. If not specified, s2pexec will use the board (initiator) ID 7.
.TP
.BR \--cdb/-c\fI " "\fICDB
SCSI command block to send in hexecimal format. Hexadecimal numbers may be separated by a colon.
.TP
.BR \--buffer-size/-b\fI " "\fIBUFFER_SIZE
TrBuffer size for receiving data. When sending data the buffer is automatically sized to match the size of the data to be sent.
.TP
.BR \--log-level/-L\fI " " \fILOG_LEVEL
Set the log level (trace, debug, info, warning, error, off). The default log level is 'info'.
.TP
.BR \--input-file/-f\fI " "\fIFILE
The protobuf data input file, by default in JSON format.
.TP
.BR \--output-file/-F\fI " "\fIFILE
The protobuf data output file, by default in JSON format. If not specified JSON data will be displayed on stdout.
.TP
.BR \--binary-data-file/-d\fI " "\fIFILE
The file to store the data received (in a DATA IN phase) in or a file with the data to be sent (in a DATA OUT phase).
The data are in binary (non human-readable) format. When no data file is specified any data received are displayed in a human-readable format.
.TP
.BR \--text-data-file/-D\fI " "\fIFILE
The file to store the data received (in a DATA IN phase) in or a file with the data to be sent (in a DATA OUT phase).
The data are in text (hexadecimal values) format. When no data file is specified any data received are displayed in a human-readable format.
.TP
.BR \--binary-input\fI
Signals that the input file is in protobuf binary format instead of JSON.
.TP
.BR \--binary-output\fI
Generate a protobuf binary format file instead of JSON.
.TP
.BR \--text-input\fI
Signals that the input file is in protobuf text format instead of JSON.
.TP
.BR \--text-output\fI
Generate a protobuf text format file instead of JSON.
.TP
.BR \--help/-H\fI
Show a help text.
.TP
.BR \--version/-v\fI
Show the s2pexec version.

.SH EXAMPLE
s2pexec -i 0 -b 65536 -c c0:01:00:00:00:00:00:ff:ff:00"
Send a command to the target device with SCSI ID 0.

.SH SEE ALSO
s2pctl(1), s2p(1), s2pdump(1)
 
Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
