.TH s2psimh 1
.SH NAME
s2psimh \- SCSI2Pi SIMH .tap File Tool
.SH SYNOPSIS
.B s2psimh
[\fB\--add/-a\fR \fICLASS1:VALUE1,...\fR]
[\fB\--dump\fR \fIDATA_FILE\fR]
[\fB\--dump/-d\fR]
[\fB\--limit/-l\fR \fILIMIT\fR]
[\fB\--truncate/-t\fR]
[\fB\--help/-h\fR]
[\fB\--version/-v\fR]
<SIMH_TAP_FILE>
.SH DESCRIPTION
.B s2psimh
analyses and manipulates SIMH .tap tape image files.

.SH NOTES

.B s2psimh
displays SIMH file contents, checks that they have a proper format, and adds new SIMH objects.

.SH OPTIONS
.TP
.BR --add/-a\fI " " \fICLASS1:VALUE1,...
Add objects.
.TP
.BR --data/\fI " " \fIDATA_FILE
An optional file to read the record data from. If this file is not specified, the data record contents are undefined.
.TP
.BR --dump/-d\fI
Dump data record contents.
.TP
.BR --limit/-l\fI " " \fILIMIT
Limit dump size to LIMIT bytes.
.TP
.BR --truncate/-t\fI
Truncate file before adding objects.
.TP
.BR --help/-h\fI
Show a help text.
.TP
.BR --version/-v\fI
Show the s2psimh version.

.SH EXIT STATUS
0:  No error. -1: There was a general error and the file could not be accessed.

.SH SEE ALSO
s2p(1), s2pctl(1), s2pdump(1), s2pexec(1), s2pproto(1)
 
Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
