.TH s2psimh 1
.SH NAME
s2psimh \- SCSI2Pi Simh .tap File Analysis Tool
.SH SYNOPSIS
.B s2psimh
[\fB\--dump/-d\fR]
[\fB\--limit/-l\fR \fILIMIT\fR]
[\fB\--help/-h\fR]
[\fB\--version/-v\fR]
<SIMH_TAP_FILE>
.SH DESCRIPTION
.B s2psimh
analyses .tap tape image files in Simh format and display the file structure.

.SH NOTES

.B s2psimh
ensures that a Simh file has a proper format.

.SH OPTIONS
.TP
.BR --dump/-h\fI
Dump record contents.
.TP
.BR --limit/-l\fI " " \fILIMIT
Limit record contents dump size to LIMIT bytes.
.TP
.BR --help/-h\fI
Show a help text.
.TP
.BR --version/-v\fI
Show the s2psimh version.

.SH EXIT STATUS
0:  No error. -1: There was a general error and the file could not be analyzed.

.SH SEE ALSO
s2p(1), s2pctl(1), s2pdump(1), s2pexec(1), s2pproto(1)
 
Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
