.TH s2pstool 1
.SH NAME
s2ptool \- SCSI2Pi In-process Tool
.SH SYNOPSIS
.B s2ptool
[\fB\--client/-c\fR \fICLIENT\fR]
[\fB\--client-args/-a\fR]
[\fB\--s2p-args/-s\fR]
[\fB\--log-signals/-l\fR]
[\fB\--help/-h\fR]
[\fB\--version/-v\fR]
.SH DESCRIPTION
.B s2ptool
Runs s2p and a selected client inside the same process.

.SH NOTES

.B s2ptool
runs s2p and the selected client in the same process. This is particular useful in order to test s2p and/or a client tool without any Pi hardware.

.SH OPTIONS
.TP
.BR --client/-c\fI " "\fICLIENT
The client tool to run against s2p (s2pctl|s2pdump|s2pexec|s2pproto), default is s2pexec.
.TP
.BR --client-args/-a\fI
Arguments to run the client tool with, optional for s2pctl and s2pexec.
.TP
.BR --s2p-args/-s\fI
Arguments to run s2p with.
.TP
.BR --log-signals/-l\fI
On log level trace also log bus signals (very verbose).
.TP
.BR --help/-h\fI
Display a help text.
.TP
.BR --version/-v\fI
Display the s2ptool version.

.SH SEE ALSO
s2p(1), s2pctl(1), s2pdump(1), s2pexec(1), s2pproto(1), s2ptool(1)
 
Also see <https://www.scsi2pi.net> and <https://github.com/uweseimet/scsi2pi>.
