//---------------------------------------------------------------------------
//
// SCSI2Pi, SCSI device emulator and SCSI tools for the Raspberry Pi
//
// Copyright (C) 2021-2025 Uwe Seimet
//
//---------------------------------------------------------------------------

#pragma once

enum class ScsiLevel
{
    NONE = 0,
    SCSI_1_CCS = 1,
    SCSI_2 = 2,
    SPC = 3,
    SPC_2 = 4,
    SPC_3 = 5,
    SPC_4 = 6,
    SPC_5 = 7,
    SPC_6 = 8,
    SPC_7 = 9,
    LAST = 10
};

enum class BusPhase
{
    BUS_FREE = 0,
    ARBITRATION = 1,
    SELECTION = 2,
    RESELECTION = 3,
    COMMAND = 4,
    DATA_IN = 5,
    DATA_OUT = 6,
    STATUS = 7,
    MSG_IN = 8,
    MSG_OUT = 9,
    RESERVED = 10
};

enum class DeviceType
{
    DIRECT_ACCESS = 0,
    SEQUENTIAL_ACCESS = 1,
    PRINTER = 2,
    PROCESSOR = 3,
    CD_DVD = 5,
    OPTICAL_MEMORY = 7
};

enum class ScsiCommand
{
    TEST_UNIT_READY = 0x00,
    REZERO = 0x01,
    REWIND = 0x01,
    REQUEST_SENSE = 0x03,
    FORMAT_UNIT = 0x04,
    FORMAT_MEDIUM = 0x04,
    READ_BLOCK_LIMITS = 0x05,
    REASSIGN_BLOCKS = 0x07,
    READ_6 = 0x08,
    GET_MESSAGE_6 = 0x08,
    // DaynaPort-specific command
    RETRIEVE_STATS = 0x09,
    WRITE_6 = 0x0a,
    SEND_MESSAGE_6 = 0x0a,
    PRINT = 0x0a,
    SEEK_6 = 0x0b,
    // DaynaPort-specific command
    SET_IFACE_MODE = 0x0c,
    // DaynaPort-specific command
    SET_MCAST_ADDR = 0x0d,
    // DaynaPort-specific command
    ENABLE_INTERFACE = 0x0e,
    READ_REVERSE = 0x0f,
    SYNCHRONIZE_BUFFER = 0x10,
    WRITE_FILEMARKS_6 = 0x10,
    SPACE_6 = 0x11,
    INQUIRY = 0x12,
    VERIFY_6 = 0x13,
    MODE_SELECT_6 = 0x15,
    RESERVE_RESERVE_ELEMENT_6 = 0x16,
    RELEASE_RELEASE_ELEMENT_6 = 0x17,
    ERASE_6 = 0x19,
    MODE_SENSE_6 = 0x1a,
    START_STOP = 0x1b,
    STOP_PRINT = 0x1b,
    SEND_DIAGNOSTIC = 0x1d,
    PREVENT_ALLOW_MEDIUM_REMOVAL = 0x1e,
    READ_FORMAT_CAPACITIES = 0x23,
    READ_CAPACITY_10 = 0x25,
    READ_10 = 0x28,
    WRITE_10 = 0x2a,
    SEEK_10 = 0x2b,
    ERASE_10 = 0x2c,
    LOCATE_10 = 0x2b,
    WRITE_AND_VERIFY_10 = 0x2e,
    VERIFY_10 = 0x2f,
    READ_POSITION = 0x34,
    SYNCHRONIZE_CACHE_10 = 0x35,
    READ_DEFECT_DATA_10 = 0x37,
    MEDIUM_SCAN = 0x38,
    WRITE_BUFFER = 0x3b,
    READ_BUFFER_10 = 0x3c,
    READ_LONG_10 = 0x3e,
    WRITE_LONG_10 = 0x3f,
    WRITE_SAME_10 = 0x41,
    READ_SUB_CHANNEL = 0x42,
    READ_TOC = 0x43,
    READ_HEADER = 0x44,
    PLAY_AUDIO_10 = 0x45,
    GET_CONFIGURATION = 0x46,
    PLAY_AUDIO_MSF = 0x47,
    PLAY_AUDIO_TRACK_INDEX = 0x48,
    GET_EVENT_STATUS_NOTIFICATION = 0x4a,
    PAUSE_RESUME = 0x4b,
    LOG_SELECT = 0x4c,
    LOG_SENSE = 0x4d,
    READ_DISC_INFORMATION = 0x51,
    READ_TRACK_INFORMATION = 0x52,
    RESERVE_RESERVE_ELEMENT_10 = 0x56,
    MODE_SELECT_10 = 0x55,
    RELEASE_RELEASE_ELEMENT_10 = 0x57,
    READ_MASTER_CUE = 0x59,
    MODE_SENSE_10 = 0x5a,
    CLOSE_TRACK_SESSION = 0x5b,
    READ_BUFFER_CAPACITY = 0x5c,
    PERSISTENT_RESERVE_IN = 0x5e,
    PERSISTENT_RESERVE_OUT = 0x5f,
    WRITE_FILEMARKS_16 = 0x80,
    REBUILD_READ_REVERSE_16 = 0x81,
    READ_16 = 0x88,
    WRITE_16 = 0x8a,
    WRITE_AND_VERIFY_16 = 0x8e,
    VERIFY_16 = 0x8f,
    SYNCHRONIZE_CACHE_SPACE_16 = 0x91,
    LOCATE_16 = 0x92,
    ERASE_WRITE_SAME_16 = 0x93,
    READ_BUFFER_16 = 0x9b,
    READ_CAPACITY_READ_LONG_16 = 0x9e,
    WRITE_LONG_16 = 0x9f,
    REPORT_LUNS = 0xa0,
    BLANK = 0xa1,
    PLAY_AUDIO_12 = 0xa5,
    READ_12 = 0xa8,
    WRITE_12 = 0xaa,
    ERASE_12 = 0xac,
    READ_DVD_STRUCTURE = 0xad,
    WRITE_AND_VERIFY_12 = 0xaf,
    VERIFY_12 = 0xaf,
    SEND_VOLUME_TAG = 0xb6,
    READ_DEFECT_DATA_12 = 0xb7,
    READ_CD_MSF = 0xb9,
    SET_CD_SPEED = 0xbb,
    PLAY_CD = 0xbc,
    READ_CD = 0xbe,
    // SCSi2Pi-specific commands (host services)
    EXECUTE_OPERATION = 0xc0,
    RECEIVE_OPERATION_RESULTS = 0xc1
};

enum class MessageCode
{
    COMMAND_COMPLETE = 0x00,
    ABORT = 0x06,
    MESSAGE_REJECT = 0x07,
    LINKED_COMMAND_COMPLETE = 0x0a,
    LINKED_COMMAND_COMPLETE_WITH_FLAG = 0x0b,
    BUS_DEVICE_RESET = 0x0c,
    IDENTIFY = 0x80
};

enum class StatusCode
{
    GOOD = 0x00,
    CHECK_CONDITION = 0x02,
    CONDITION_MET = 0x04,
    BUSY = 0x08,
    INTERMEDIATE = 0x10,
    INTERMEDIATE_CONDITION_MET = 0x14,
    RESERVATION_CONFLICT = 0x18,
    COMMAND_TERMINATED = 0x22,
    QUEUE_FULL = 0x28,
    ACA_ACTIVE = 0x30,
    TASK_ABORTED = 0x40
};

enum class SenseKey
{
    NO_SENSE = 0x00,
    RECOVERED_ERROR = 0x01,
    NOT_READY = 0x02,
    MEDIUM_ERROR = 0x03,
    HARDWARE_ERROR = 0x04,
    ILLEGAL_REQUEST = 0x05,
    UNIT_ATTENTION = 0x06,
    DATA_PROTECT = 0x07,
    BLANK_CHECK = 0x08,
    VENDOR_SPECIFIC = 0x09,
    COPY_ABORTED = 0x0a,
    ABORTED_COMMAND = 0x0b,
    EQUAL = 0x0c,
    VOLUME_OVERFLOW = 0x0d,
    MISCOMPARE = 0x0e,
    RESERVED = 0x0f
};

enum class Asc
{
    NO_ADDITIONAL_SENSE_INFORMATION = 0x00,
    WRITE_FAULT = 0x03,
    IO_PROCESS_TERMINATED = 0x06,
    WRITE_ERROR = 0x0c,
    READ_ERROR = 0x11,
    LOCATE_OPERATION_FAILURE = 0x14,
    PARAMETER_LIST_LENGTH_ERROR = 0x1a,
    INVALID_COMMAND_OPERATION_CODE = 0x20,
    LBA_OUT_OF_RANGE = 0x21,
    INVALID_FIELD_IN_CDB = 0x24,
    LOGICAL_UNIT_NOT_SUPPORTED = 0x25,
    INVALID_FIELD_IN_PARAMETER_LIST = 0x26,
    WRITE_PROTECTED = 0x27,
    NOT_READY_TO_READY_TRANSITION = 0x28,
    POWER_ON_OR_RESET = 0x29,
    INCOMPATIBLE_MEDIUM_INSTALLED = 0x30,
    SEQUENTIAL_POSITIONING_ERROR = 0x38,
    MEDIUM_NOT_PRESENT = 0x3a,
    INTERNAL_TARGET_FAILURE = 0x44,
    COMMAND_PHASE_ERROR = 0x4a,
    DATA_PHASE_ERROR = 0x4b,
    MEDIUM_LOAD_OR_EJECT_FAILED = 0x53,
    DATA_CURRENTLY_UNAVAILABLE = 0x55
};

enum class Ascq
{
    NONE = 0x00,
    FILEMARK_DETECTED = 0x01,
    END_OF_PARTITION_MEDIUM_DETECTED = 0x02,
    BEGINNING_OF_PARTITION_MEDIUM_DETECTED = 0x04,
    END_OF_DATA_DETECTED = 0x05,
};
